package it.crem.db.conf;

import java.text.SimpleDateFormat;
import java.util.Date;

import it.crem.db.BaseObject;

// Generated May 1, 2016 7:22:17 PM by Hibernate Tools 3.4.0.CR1

/**
 * Presenze generated by hbm2java
 */
public class Presenze extends BaseObject implements java.io.Serializable {

	//private Giornate giornate;
	private Ragazzi ragazzi;
	private Boolean completo;
	private Boolean mensa;
	private Boolean mattina;
	private Boolean pomeriggio;
	private Date giorno = null;
	private Boolean presente = null;
	private static SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
	
	public Presenze() {
	}

	

	

	/*
	public Giornate getGiornate() {
		return this.giornate;
	}

	public void setGiornate(Giornate giornate) {
		this.giornate = giornate;
	}
	 */
	public Ragazzi getRagazzi() {
		return this.ragazzi;
	}

	public void setRagazzi(Ragazzi ragazzi) {
		this.ragazzi = ragazzi;
	}

	public Boolean getCompleto() {
		return this.completo;
	}

	public void setCompleto(Boolean completo) {
		this.completo = completo;
	}

	public Boolean getMensa() {
		return this.mensa;
	}

	public void setMensa(Boolean mensa) {
		this.mensa = mensa;
	}

	public Boolean getMattina() {
		return this.mattina;
	}

	public void setMattina(Boolean mattina) {
		this.mattina = mattina;
	}

	public Boolean getPomeriggio() {
		return this.pomeriggio;
	}

	public void setPomeriggio(Boolean pomeriggio) {
		this.pomeriggio = pomeriggio;
	}

	public Date getGiorno() {
		return giorno;
	}

	public void setGiorno(Date giorno) {
		this.giorno = giorno;
	}





	public Boolean getPresente() {
		return presente;
	}





	public void setPresente(Boolean presente) {
		this.presente = presente;
	}
	public String getFormattedGiorno(){
		if (giorno!=null)
			return sdf.format(giorno);
		else
			return "";
	}

}
