package it.crem.db.conf;

// Generated May 1, 2016 7:22:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Giornate generated by hbm2java
 */
public class Giornate implements java.io.Serializable {

	private int oid;
	private Periodi periodi;
	private Date giorno;
	private Set presenzes = new HashSet(0);

	public Giornate() {
	}

	public Giornate(int oid) {
		this.oid = oid;
	}

	public Giornate(int oid, Periodi periodi, Date giorno, Set presenzes) {
		this.oid = oid;
		this.periodi = periodi;
		this.giorno = giorno;
		this.presenzes = presenzes;
	}

	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	public Periodi getPeriodi() {
		return this.periodi;
	}

	public void setPeriodi(Periodi periodi) {
		this.periodi = periodi;
	}

	public Date getGiorno() {
		return this.giorno;
	}

	public void setGiorno(Date giorno) {
		this.giorno = giorno;
	}

	public Set getPresenzes() {
		return this.presenzes;
	}

	public void setPresenzes(Set presenzes) {
		this.presenzes = presenzes;
	}

}
