package it.crem.db.conf;

import it.crem.db.BaseObject;

// Generated May 1, 2016 7:22:17 PM by Hibernate Tools 3.4.0.CR1

/**
 * Partecipanti generated by hbm2java
 */
public class Partecipanti extends BaseObject implements java.io.Serializable, Comparable{

	private int oid;
	private Tipologie tipologie;
	private Periodi periodi;
	private Ragazzi ragazzi;
	private Boolean stato=false;

	public Partecipanti() {
	}

	public Partecipanti(int oid) {
		this.oid = oid;
	}

	public Partecipanti(int oid, Tipologie tipologie, Periodi periodi,
			Ragazzi ragazzi) {
		this.oid = oid;
		this.tipologie = tipologie;
		this.periodi = periodi;
		this.ragazzi = ragazzi;
	}

	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	public Tipologie getTipologie() {
		return this.tipologie;
	}

	public void setTipologie(Tipologie tipologie) {
		this.tipologie = tipologie;
	}

	public Periodi getPeriodi() {
		return this.periodi;
	}

	public void setPeriodi(Periodi periodi) {
		this.periodi = periodi;
	}

	public Ragazzi getRagazzi() {
		return this.ragazzi;
	}

	public void setRagazzi(Ragazzi ragazzi) {
		this.ragazzi = ragazzi;
	}

	public Boolean getStato() {
		return stato;
	}

	public void setStato(Boolean stato) {
		this.stato = stato;
	}

	@Override
	public int compareTo(Object o) {
		// TODO Auto-generated method stub
		Partecipanti p = (Partecipanti)o;
		if (p.getOid()==oid)
			return 0;
		else
			if (p.getOid()>oid)
				return 1;
			else
				return -1;
	}

}
