package it.crem.db.conf;

// Generated May 1, 2016 7:22:17 PM by Hibernate Tools 3.4.0.CR1

import it.crem.db.BaseObject;

import java.util.HashSet;
import java.util.Set;

/**
 * Tipologie generated by hbm2java
 */

public class Tipologie extends BaseObject implements java.io.Serializable {

	private int oid;
	private String forma;
	private Double costoUnitario;
	private Double costoTotale;
	private String tipo; 
	private Integer numSettimane;
	private Boolean familiare;
	private Boolean mensa;
	private Boolean fullDay;
	
	private Set partecipantis = new HashSet(0);

	public Tipologie() {
	}

	public Tipologie(int oid) {
		this.oid = oid;
	}

	public Tipologie(int oid, String forma, Double costoUnitario,
			Double costoTotale, Set partecipantis) {
		this.oid = oid;
		this.forma = forma;
		this.costoUnitario = costoUnitario;
		this.costoTotale = costoTotale;
		this.partecipantis = partecipantis;
	}

	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	public String getForma() {
		return this.forma;
	}

	public void setForma(String forma) {
		this.forma = forma;
	}

	public Double getCostoUnitario() {
		return this.costoUnitario;
	}

	public void setCostoUnitario(Double costoUnitario) {
		this.costoUnitario = costoUnitario;
	}

	public Double getCostoTotale() {
		return this.costoTotale;
	}

	public void setCostoTotale(Double costoTotale) {
		this.costoTotale = costoTotale;
	}

	public Set getPartecipantis() {
		return this.partecipantis;
	}

	public void setPartecipantis(Set partecipantis) {
		this.partecipantis = partecipantis;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getNumSettimane() {
		return numSettimane;
	}

	public void setNumSettimane(Integer numSettimane) {
		this.numSettimane = numSettimane;
	}

	public Boolean getFamiliare() {
		return familiare;
	}

	public void setFamiliare(Boolean familiare) {
		this.familiare = familiare;
	}

	public Boolean getMensa() {
		return mensa;
	}

	public void setMensa(Boolean mensa) {
		this.mensa = mensa;
	}

	public Boolean getFullDay() {
		return fullDay;
	}

	public void setFullDay(Boolean fullDay) {
		this.fullDay = fullDay;
	}

}
