package it.crem.db.conf;
// Generated Jan 21, 2015 6:48:14 PM by Hibernate Tools 3.4.0.CR1


import it.crem.db.BaseObject;

import java.util.HashSet;
import java.util.Set;

/**
 * Societa generated by hbm2java
 */
public class Utenti  extends BaseObject implements java.io.Serializable {


     private String login;
     private String password;
     private String email;
     private String nome;
     private String cognome;
	public String getLogin() {
		return login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getCognome() {
		return cognome;
	}
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}
     
     

}


